language: objective-c

xcode_project: swift3D.xcodeproj
xcode_scheme: swift3D-Mac
osx_image: xcode7.1
xcode_sdk: macosx10.11

script:
- xcodebuild test -project swift3D.xcodeproj -scheme swift3D-Mac \
    GCC_GENERATE_DEBUGGING_SYMBOLS=YES \
    GCC_GENERATE_TEST_COVERAGE_FILES=YES \
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
